### ISSUE TITLE
Add doc for how it compares to criterium

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/tufte#1]
Criterium is likely to be the other Clojure profiling tool people think of when they read this README. It could be good to mention how they compare and contrast.

**Comment by ptaoussanis** [comment]
Good idea, thanks!

**Comment by ptaoussanis** [comment]
https://github.com/ptaoussanis/tufte/tree/c16f85010f3528856e4a247615b6121f9890343c#how-does-tufte-compare-to-hugoduncancriterium
