### ISSUE TITLE
Documentation request: how might one use `p`, `defnp` in protocol methods?

### ISSUE THREAD

**Issue by ncalexan** [ptaoussanis/tufte#12]
I would like to profile methods that are completing a protocol definition.  For example, if I have
```
(defprotocol P
  (method [argument]))

(defrecord ConcreteP [member]
  P
  (method [argument] ...))
```
how would you suggest adding `tufte` wrapping to `ConcreteP`'s implementation of `method`?  Is the best that can be done to wrap it in `p` manually?

**Comment by ptaoussanis** [comment]
Hi Nick,

> Is the best that can be done to wrap it in p manually?

Yeah, that's correct. So something like `(method [arg] ...)` -> `(method [arg] (p :foo ...))` would be quite idiomatic.

Cheers! :-)
