### ISSUE TITLE
Clarification w.r.t. multithreaded profiling

### ISSUE THREAD

**Issue by ValerieAnne563** [ptaoussanis/tufte#14]
Thanks for tufte, it's been useful in profiling a pretty complicated call stack.

In the best practices of profiling, it may be worth reminding folks that when dealing with lazy sequences, the accumulated time of expressions that generate lazy sequences will be attributed to the caller of said lazy sequence. This can be a good thing, as functions that use the lazy sequences wisely (transducers, taking only what's needed, etc) will show up with a better runtime than those who use them wastefully (realizing the entire sequence into memory).

However, if there is something inherently expensive about how the lazy sequence acquires its values, that will not be apparent. 

Not a tufte thing, really a Clojure thing. But worth mention, might be a pitfall that others will encounter.

Example at bottom of:
http://stackoverflow.com/questions/40643118/how-to-profile-multithreaded-clojure-results-with-tufte

**Comment by ptaoussanis** [comment]
Hi Valerie, you're very welcome- thanks for saying so :-)

Really sorry about the long delay replying.

> it may be worth reminding folks that when dealing with lazy sequences,

Thought this was already mentioned in the doc-strings but indeed wasn't, thanks for the catch (and suggestion) - will do!

Cheers :-)
