### ISSUE TITLE
Trouble getting README example to work with Cursive on IntelliJ

### ISSUE THREAD

**Issue by gurganious** [ptaoussanis/tufte#17]
Probably user error but could not get the 10-second example to output anything.
Platform: Using Cursive Plugin on IntelliJ on Windows 10

Code:
(ns example
  (:gen-class))

;; 10-second example
(require '[taoensso.tufte :as tufte :refer (defnp p profiled profile)])

;; We'll request to send `profile` stats to `println`:
(tufte/add-basic-println-handler! {})

;;; Let's define a couple dummy fns to simulate doing some expensive work
(defn get-x [] (Thread/sleep 500)             "x val")
(defn get-y [] (Thread/sleep (rand-int 1000)) "y val")

;; How do these fns perform? Let's check:

(profile ; Profile any `p` forms called during body execution
  {} ; Profiling options; we'll use the defaults for now
  (dotimes [_ 5]
    (p :get-x (get-x))
    (p :get-y (get-y))))

(println "done") ; added to confirm where *out* goes to

Resulting Output:
done

**Comment by ptaoussanis** [comment]
Hi there, thanks for the report - and sorry for the delay replying!

Sorry, not too familiar with Cursive. Example works on my end with Emacs, and (I believe) should work okay with something like Cursive if `tufte/add-basic-println-handler!` has indeed been called.

Could anyone other Cursive users possibly confirm this problem or offer debugging ideas?
