### ISSUE TITLE
No such var: enc/max-long

### ISSUE THREAD

**Issue by ashercoren** [ptaoussanis/tufte#23]
I'm trying to run your [10 seconds example](https://github.com/ptaoussanis/tufte#10-second-example), but when running `(require '[taoensso.tufte :as tufte :refer (defnp p profiled profile)])` I get an error: `CompilerException java.lang.RuntimeException: No such var: enc/max-long, compiling:(taoensso/tufte/impl.cljc:122:20)`.

I'm using Clojure 1.8.0

**Comment by aengelberg** [comment]
Also getting this error, but on Clojure 1.9.

**Comment by aengelberg** [comment]
If I explicitly add the dependency `[com.taoensso/encore "2.94.0"]` that fixes it.

**Comment by ptaoussanis** [comment]
Yes, this indicates a dependency conflict- please see https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md for more info :-)
