### ISSUE TITLE
Clojure 1.6 compatibility

### ISSUE THREAD

**Issue by yayitswei** [ptaoussanis/tufte#25]
Is there any way to make tufte compatible with Clojure 1.6? I've been getting this error (not reproducible on Clojure 1.7+):

```
user=> FileNotFoundException Could not locate taoensso/tufte__init.class or taoensso/tufte.clj on classpath:   clojure.lang.RT.load (RT.java:443)
```

Thanks for making this! I've found it super useful.

**Comment by yayitswei** [comment]
Ah nevermind, I hacked together a working 1.6 version by manually creating `clj` files out of the `cljc` files. If you know of a more elegant solution please let me know, but in the meantime my issue is fixed!

**Comment by ptaoussanis** [comment]
Hi Wei, approach you took (splitting clj/s files) sounds good if that works- thanks for following up!

Am curious: any particular reason you're stuck with <1.7?

**Comment by yayitswei** [comment]
Legacy codebase :) There are too many dependencies to upgrade for the time
being. If anyone finds it useful, I could clean up and publish the 1.6
version of tufte.
