### ISSUE TITLE
Profiling ClojureScript async code

### ISSUE THREAD

**Issue by mjmeintjes** [ptaoussanis/tufte#26]
Is it possible to use this library to profile ClojureScript async/promise type code?

For example, I'm using promesa library, and would like to profile how long an entire promise chain takes.

This means I need to be able to start the profiler before setting up the promise, and then stop the profiler when the promise resolves (which might not happen until much later).

As far as I understand, the current dynamic binding setup won't work for this. 

Is this something that this library supports?

**Comment by ptaoussanis** [comment]
Hi there,

Yes, this is possible- most easily using a low-level `capture-times!` utility fn just added in 1.2.0. Will try update here later with a proper example, otherwise someone else may be able to assist.

**Comment by ptaoussanis** [comment]
Hi, just checking if you were able to figure out how to use `capture-times!` or if you still need assistance? Thanks

**Comment by mjmeintjes** [comment]
Sorry for not replying earlier.

I tried using capture-times! for my situation. Unfortunately I couldn't get it to work, as it still requires a top level form to apply `profile` to, but as my Clojurescript code is async there isn't really any form that encompasses the entire execution time.

What I ended up doing is the following:
```
(def profiles! (atom {}))
(defn start-timer
  [k]
  (swap! profiles! assoc k (js/performance.now)))

(defn elapsed-time
  [k]
  (let [start (get @profiles! k)
        now (js/performance.now)]
    (- now start)))
```

**Comment by mjmeintjes** [comment]
Feel free to close this issue.

**Comment by ptaoussanis** [comment]
@mjmeintjes Hi Matt, recently made this a bit easier to do with the inclusion of [this fn](https://github.com/ptaoussanis/tufte/blob/38e061a51fbf2678477f79a20d248abe16a0e355/src/taoensso/tufte.cljc#L241).

Usage example:

```clojure
(let [pd (tufte/new-pdata)]
  (tufte/capture-time! pd :id <time-nanosecs>) ; From anywhere
  @@pd ; Get stats
)
```

Hope that helps, cheers!
