### ISSUE TITLE
Problem compiling ClojureScript with 2.0.0

### ISSUE THREAD

**Issue by atroche** [ptaoussanis/tufte#27]
Hello! Long time com.taoensso fan, first time issue submitter.

When I include `2.0.0` as a dependency and require `taoensso.tufte` using Figwheel for compilation I get this:

![image](https://user-images.githubusercontent.com/29839/39355686-746955f8-4a40-11e8-97a3-7bb1f08dc3a3.png)

With the exact same setup but the dep changed to `1.4.0` it works fine.

**Comment by ptaoussanis** [comment]
@atroche Hey Alistair, thanks for the report (and for the PR!).

Just cut `[com.taoensso/tufte "2.0.1"]` which should resolve this 👍

Cheers :-)
