### ISSUE TITLE
Difficulties using both tufte and timbre

### ISSUE THREAD

**Issue by stubillwhite** [ptaoussanis/tufte#3]
Hi,

I seem to be having some problems running both timbre and tufte at the same time. Both are at the latest version and both work in isolation, but when both libraries are :require'd then I see the following error "defnp already refers to: #'taoensso.timbre.profiling/defnp in namespace: profiling.core"

I've attached a ZIP of the project. I'm using Clojure 1.7, tufte 1.0.0-RC2, and timbre 4.6.0, which I think are the latest versions. If there's anything else I can do to help then please let me know.

Finally, thank you for tufte -- it looks excellent, and I'm looking forward to experimenting with it more.

[profiling.zip](https://github.com/ptaoussanis/tufte/files/367745/profiling.zip)

**Comment by ptaoussanis** [comment]
Hi there,

This is a namespace import issue. `taoensso.timbre.profiling` and `taoensso.tufte` both have vars with the same names (e.g. `defnp`) that'll clash if you try to :refer them both.

You'll want to remove your namespace :refer imports for one or the other (or both).

Does that make sense?

**Comment by stubillwhite** [comment]
That makes perfect sense - thank you for clarifying, and for the fast response.

**Comment by stubillwhite** [comment]
That makes perfect sense - thank you for clarifying, and for the fast response.
