### ISSUE TITLE
Enable global profiling.

### ISSUE THREAD

**Issue by j-pb** [ptaoussanis/tufte#34]
Hey,
I just tried to upgrade to the latest version,
but can't get our use case to work anymore since 
`tufte/start-profiling-thread!` and `tufte/stop-profiling-thread!`
got removed.
So this is basically a continuation of  #[5] :/

The issue that we have is that we're running a pedestal GraphQL endpoint, which dispatches functions to an agent, which will asynchronously handle them.
We wrapped the GraphQL handlers into `profile` calls, but it seems that by the time the agent gets to process the code of interest, the code that originally dispatched it, has exited, taking the dynamic var to enable profiling with it.

Is there any way we can enable per thread profiling? Or just profiling globally?
There doesn't seem to be an actual var root we could alter, so we're a bit out of ideas :/

Any thoughts and ideas?

**Comment by ptaoussanis** [comment]
Hi Jan-Paul,

You're talking about an upgrade from 1.x to 2.x?

The following low-level primitives are public and might be useful:
`new-pdata`, `with-profiling`, `capture-time!`.

In particular please take a look at the docstring of `new-pdata` (which
includes a short example of use), and let me know if that helps?

2.x should be strictly more flexible than 1.x, but could require some
migration- esp. if you were using low-level primitives from 1.x

**Comment by ptaoussanis** [comment]
Assuming this was answered so going to close, but please feel free to reopen otherwise!
