### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by loganpowell** [ptaoussanis/tufte#36]
Hi! Looking forward to trying this out, but I'm having a hard time wrapping my head around the various ways to use this. I've dug through some of the other issues (most notably [this one](https://github.com/ptaoussanis/tufte/issues/26#issuecomment-383318792)) but figured I'd just ask: Could you put some complete examples together for how we could use `tufte`? The only examples I could find where in the [tests](https://github.com/ptaoussanis/tufte/blob/38e061a51fbf2678477f79a20d248abe16a0e355/test/taoensso/tufte_tests.clj) directory, but I'm wondering if you have code laying around with tufte included that we could learn from...

**Comment by ivarref** [comment]
What kind of examples are you looking for? For the JVM or for JavaScript?

I'm using tufte in JVM-land for a web-server. I have something like the following inside all my [yada handlers](https://github.com/juxt/yada) (added using postwalk):

```clojure
(let [[res pstats] (profiled {}
                             (p ::response-fn
                                (response-fn ctx)))
      pstats @pstats
      clock-total-ms (long (/ (long (get-in pstats [:clock :total])) 1e6))]
  (when log-performance
    (log/with-logging-context {"responseTime" (str clock-total-ms)}
                              (log/info (str "performance:\n\n" (tufte/format-pstats pstats)))))
  res)
```

The functions I'm particularly interested in is written using `tufte/defnp`, which is like `defn` but wraps fn bodies with `p` macro.

**Comment by loganpowell** [comment]
I'm working in ClojureScript. I'm currently hitting JS VM heap limits and looking for opportunities to triage the most inefficient code. I love the idea of having `tufte` live as a part of the code and only activate it when testing. Those are the kinds of examples that would really help. Even if for toy examples.

**Comment by ivarref** [comment]
Right. So the README have a section on [conditional profiling](https://github.com/ptaoussanis/tufte#conditional-profiling).

That said the current version is broken on JavaScript unfortunately, see issue #33.

**Comment by loganpowell** [comment]
Thank you @ivarref for following up.

**Comment by ptaoussanis** [comment]
Just added a small [Example project](https://github.com/ptaoussanis/tufte/tree/master/examples/clj), hope that might help!

Cheers :-)
