### ISSUE TITLE
format-pstats: Allow id to be stringified by a custom function

### ISSUE THREAD

**Issue by ivarref** [ptaoussanis/tufte#38]
Motivating case: 
My code is sprinkled with `defnp`. All my function names are unique. All of my namespaces share the same top level namespace. Printing the full namespace plus defn plus function name is a little verbose and not really needed for this case.

Allow for something like `format-id-fn` that will be called inside `format-pstats` on `id`. It's then up to the user of the library to choose formatting, for example to remove or abbreviate namespace.

Future work: One could support setting `format-id-fn` to `:abbr` and supply a default abbrevation function.

**Comment by ivarref** [comment]
I'm closing this as it's now implemented on master branch.

**Comment by ptaoussanis** [comment]
@ivarref Hi Ivar,

Could I please request that we avoid merging things into master until I've had an opportunity to review? I know I can be a little slow to respond, and that that can be frustrating. Maybe you could run a fork in the meantime if you need new releases more urgently?

Am expecting to have an opportunity to batch some open-source work pretty soon, and some attention for Tufte will be near the top of the list.

Really appreciate all your work!
