### ISSUE TITLE
Add sensible default implementation for format-id-fn

### ISSUE THREAD

**Issue by ivarref** [ptaoussanis/tufte#41]

**Comment by ptaoussanis** [comment]
@ivarref Hi Ivar, how are we doing with this? Would like to consider cutting `[com.taoensso/tufte "2.1.0"]` this weekend if there's no outstanding issues with RC2?

**Comment by ivarref** [comment]
Hi Peter,

And thanks for following up on this and other issues.
Did you see the branch on the formatting function? Do you consider this a
reasonable default?

https://github.com/ptaoussanis/tufte/tree/format-id-abbr?files=1

Or this could be provided as a built-in alternative.

It’s been a little busy for me lately, but I could try to tweak / look over
that function tonight or tomorrow.

Regards.

**Comment by ptaoussanis** [comment]
PR merged
