### ISSUE TITLE
stats-accumulator should not drop items with empty group id

### ISSUE THREAD

**Issue by ivarref** [ptaoussanis/tufte#44]
Hi, and thanks once again for a fine library.

I found the following behaviour counterintuitive:
```clojure
(do (def my-sacc (add-accumulating-handler! {}))
    (profile {} (p :p1 (Thread/sleep 3000)))
    (deref my-sacc))
=> {}
```

whereas giving an id gives the the expected result:
```clojure
(do (def my-sacc (add-accumulating-handler! {}))
    (profile {:id :foo} (p :p1 (Thread/sleep 3000)))
    (deref my-sacc))
=> {:foo #object[taoensso.tufte.impl.PStats 0x635ab1cb {:status :pending, :val nil}]}
```

A solution could be to provide a default value for `id` in `profile`, for example `:default`?

**Comment by ptaoussanis** [comment]
Nice catch, thanks. Can close after https://github.com/ptaoussanis/tufte/commit/cddd614c9a9fd15b313ea16efa3981f03b58a8cc?
