### ISSUE TITLE
Background profiling.

### ISSUE THREAD

**Issue by j-pb** [ptaoussanis/tufte#5]
We're running a setup where we have a single thread processing messages in the background.
We'd like to use tufte to profile this thread for a certain amount of time, to see how it behaves under load. However since this is a continuously running thread we have no toplevel form it returns to, to do a 'profile' or 'profiled' call.
Any ideas if and how this is possible?

**Comment by ptaoussanis** [comment]
Hi there,

> we have no toplevel form it returns to

Not sure I follow; presumably there's some point where you write code for what happens in the background thread? That's the code you'd want to wrap.

Otherwise, see `tufte/start-profiling-thread!`, `tufte/stop-profiling-thread!`.

Hope that helps.

**Comment by j-pb** [comment]
Yeah the problem there is that the code is not meant to terminate and running in a very tight loop.
It looks basically like this:

``` clojure
(def transactor
    (doto (Thread.
                   (while (not (Thread/interrupted)
                       (let [msg (take-message input-queue)
                               result (p :message-handler (handle-message msg)]
                           (put-message output-queue result))))
              (.run)))
```

What we'd like to do is run profiling in the background continuously and then being able to check the current statistics, or the ability to enable profiling for a certain amount of time from the outside.

**Comment by j-pb** [comment]
We kinda solved it now by sending special messages that start and stop profiling, it's not ideal but workable :)

**Comment by ptaoussanis** [comment]
Thanks for the follow-up, cheers :-)

**Comment by j-pb** [comment]
Thanks a lot for this very cool library :D

**Comment by ptaoussanis** [comment]
You're very welcome, thanks for saying so.
