### ISSUE TITLE
Alternative approximation for total clock time

### ISSUE THREAD

**Issue by ivarref** [ptaoussanis/tufte#50]
Hi, and thanks once again for a fine library.

Currently I'm running tufte in production in a moderately busy webserver. At the most busy endpoint, `[:clock :approx]` keeps becoming `true`. I'm not sure exactly why this keeps happening, I'm guessing because of context switches / concurrent access at that endpoint. Most of the time the webserver is idle though. Due to the current approx time strategy, the percentage total in format pstats drop to about zero. The estimated time basically becomes the timespan of the pstats accumulator.

I have a proposed fix for this (see pull request). This strategy supports "bouncing back" from an occasional unordered pstat, yet keeping the user informed about that total time is now an estimate.

On a bigger note: Would it make sense to calculate percentage total based on accounted total, and not clock total?

Thanks and kind regards.

**Comment by ptaoussanis** [comment]
Hi @ivarref,

> At the most busy endpoint, `[:clock :approx]` keeps becoming `true`. I'm not sure exactly why this keeps happening

Have you tried using a serialization mechanism, e.g. agent? This is the strategy used by the built-in accumulator, for example.

**Comment by ptaoussanis** [comment]
> On a bigger note: Would it make sense to calculate percentage total based on accounted total, and not clock total?

Will come back to you on this.

**Comment by ivarref** [comment]
> Hi @ivarref,
> 
> > At the most busy endpoint, `[:clock :approx]` keeps becoming `true`. I'm not sure exactly why this keeps happening
> 
> Have you tried using a serialization mechanism, e.g. agent? This is the strategy used by the built-in accumulator, for example.

No, I did not try that. Thanks for the tip. I don't quite see how that would solve the sorting issue though.

For example if I run:
```clojure
(let [s (add-accumulating-handler! "*")]
    (doall (pmap (fn [_] (profile {:id :foo} (p :bar (Thread/sleep (* 10 (Math/abs (Math/random))))))) (range 1 10)))
    (Thread/sleep 100)
    (some->> @s :foo (deref) :clock))
; => {:t0 274613975625580, :t1 274613981082891, :total 5457311, :approx? true}
```

Does that make sense? The Thread/sleep is not even needed to reproduce the error, but just to pretend to do some work.

Thanks.

**Comment by ptaoussanis** [comment]
This shouldn't be necessary any more since #52 should be addressed on `master`.
Closing for now, please feel free to re-open if there's still any issue/s. Thanks!
