### ISSUE TITLE
Incorrect calculation of total time in some cases

### ISSUE THREAD

**Issue by ivarref** [ptaoussanis/tufte#52]
Consider 

```clojure
(let [s (add-accumulating-handler! "*")]
  (profile {:id :foo} (p :p1))
  (future (Thread/sleep 800) (profile {:id :foo} (p :p1)))
  (future                    (profile {:id :foo} (p :p1 (Thread/sleep 1000))))
  (Thread/sleep 1100)
  (some-> @s :foo (deref) :clock (update :total (fn [x] (str (int (/ x 1e6)) "ms"))))
  )
; => {:t0 286335903741125, :t1 286336908179460, :total "200ms", :approx? false}
```

Total time reported here is 200 ms, but should be at least 1000 ms. The problem in `merge-pstats` is that it seems `ps0-tsum` is assumed to have accounted for everything between ps0-t0 and ps0-t1. Unfortunately I don't see how it is possible to solve this correctly using the current strategy of discarding individual t0 and t1 during `merge-pstats`.

**Comment by ptaoussanis** [comment]
Should be addressed now on master, have adopted your solution from #35.

Thanks! Closing for now, please feel free to re-open if there's still any issue/s. Thanks!
