### ISSUE TITLE
[cljs] Wrong number of args (11) passed to taoensso.tufte/HandlerVal

### ISSUE THREAD

**Issue by Wonko7** [ptaoussanis/tufte#56]
Hi! 
With version 2.1.0, using the 10 second example code emits the following warning: 
`Wrong number of args (11) passed to taoensso.tufte/HandlerVal`

**Comment by ptaoussanis** [comment]
Hi there!

Could you please try `lein clean` and `lein cljsbuild clean`, etc. first to make sure you don't have any stale build artifacts? Thanks!

**Comment by Wonko7** [comment]
Hi!
It was an interaction with another module, sorry for the noise.

**Comment by ptaoussanis** [comment]
No worries, thanks for updating! 👍
