### ISSUE TITLE
Obtain stats map formatted as string representing the time measurement.

### ISSUE THREAD

**Issue by stLalo** [ptaoussanis/tufte#58]
## Description
I am profiling several forms in my application, such as downloading a dataset from AWS s3, processing the file, upserting to the database, and send data over Kafka. I have a handler that will obtain the stats and will index the stats into Elasticsearch. However, the stats map format is plain integers and I would like to format them into strings such as when the stats are printed to stdout using `(tufte/add-basic-println-handler! {})`.

## My code
My handler looks like this
```
(defn process-stats
   "Process stats is a handler for tufte. Tufte profiles the statistic of benchmark criteria and passes the stats into the specified handler."
   [event]
   (let [pstats @(:pstats event)
         stats (get-in pstats [:stats])
         event-name (first (keys stats))
         clock (get-in pstats [:clock])
         stats (-> stats
                   (get event-name)
                   (assoc :time (datetime/now-str))
                   (assoc :event-name event-name))]
     (index-stats stats)))

(defn profile-event
  [event event-name]
  (profile {}
           (p event-name event)))

``` 

I am profiling as the following:
```
(profile-event (s3/get-file file-metadata) :s3-file)
```

It works fine and as expected, however, I can't figure the proper way to format the stats map values into strings and the time measurement

## Expected output
```
{:min "150ns",
 :event-name :s3-file,
 :mean "150ns", 
 :p75 "150ns", 
 :p99 "150ns",
 :n 1,
 :time "2020-02-19T02:51:32Z",
 :p25 "150ns",
 :p90 "150ns",
 :max "150ns",
 :p50 "150ns",
 :p95 "150ns"}
```

## actual output
```
{:min 150, :event-name :s3-file, :mean 150.0, :p75 150, :mad-sum 0.0, :p99 150, :n 1, :time "2020-02-19T02:51:32Z", :p25 150, :p90 150, :max 150, :mad 0.0, :p50 150, :sum 150, :p95 150}


pId           nCalls        Min      50% ≤      90% ≤      95% ≤      99% ≤        Max       Mean   MAD      Clock  Total

:s3-file           1   150.00ns   150.00ns   150.00ns   150.00ns   150.00ns   150.00ns   150.00ns   ±0%   170.00ns     0%

Accounted                                                                                                 150.00ns     0%
Clock                                                                                                      58.31μs   100%

```

**Comment by stLalo** [comment]
I was able to just obtain the pstats as a string and run a regex on it to get the time measure
```
str-stats (tufte/format-pstats pstats)
time-measure (re-find #"ms|μs|ns|\d+m\s+|\d+s\s+" str-stats)
```

Anyway, I found a possible scenario that could be a potential bug. 

## Description
I have a function that reads messages from Redis and it then reads the messages checks if the entity is not empty. Then, the data from the message is passed over to a router function that will call a function depending on the keyword `:processor` . The function will take on the data from the message and it will do computations under another `(go  block)`.

##Example
```
(async/go
      (when-let [data (<! records)]
        (profile-event
         (doseq [dat (:payload data)]
           (if-not (empty? (:entity dat))
             (router dat)
             (forecasts-logging {:message "Empty entity"}))) "forecasts")))
```

**Comment by ptaoussanis** [comment]
Hi there!

> I was able to just obtain the pstats as a string and run a regex on it to get the time measure

👍 

Another possibility would be to take a look at the `taoensso.tufte.stats` namespace which has some formatting functions that you could steal if you like. This could be more robust than trying to extract values via regex.

> Anyway, I found a possible scenario that could be a potential bug.

Thanks for pinging. Please see the `profile`/`profiled` [docstrings](https://ptaoussanis.github.io/tufte/taoensso.tufte.html#var-profile) for info on profiling async code:

> Async code:
>  Execution time of any code in body that runs asynchronously on a
>  different thread will generally NOT be automatically captured by default.
>
>  :dynamic? can be used to support capture in cases where Clojure's
>  binding conveyance applies (e.g. futures, agents, pmap).
>
>  In other advanced cases (notably core.async `go` blocks), please see
>  `with-profiling` and `capture-time!`.

Hope that helps!
