### ISSUE TITLE
Empty results while profiling substantial code

### ISSUE THREAD

**Issue by vemv** [ptaoussanis/tufte#60]
## Problem statement

While profiling "substantial" code (as opposed to a trivial example, which does work for me), no results are printed at all.

Note that I don't hit the profiled defns directly, but through my web framework of choice instead.

This happens in a large codebase, where I know that there are `clojure.core.async/go` blocks and other types of concurrency.

## Things tried

* Running tufte OOTB
* Running tufte with the `:dynamic? true` option

## Possible cause

Binding conveyance doesn't work across `go` blocks, and sometimes across vanilla `fn`s (which is why `clojure.core/bound-fn` exists)

My impression is: there's a missing mechanism for capturing truly arbitrary multi-threaded events?

I know that in a production app this wouldn't be a good idea since results could easily get mixed up. But in the context of running a one-off performance analysis in the REPL, in a `deftest` (assuming a sequencial test runner), etc this can be considered safe.

Thanks  - V

**Comment by vemv** [comment]
Just in case, found the doc now and was able to code something that apparently works correctly

**Comment by ptaoussanis** [comment]
Hi there!

> This happens in a large codebase, where I know that there are clojure.core.async/go blocks and other types of concurrency.

As you suspected, that's where your problem is. If you're using things like `go` blocks, then there's no way for Tufte to automatically know precisely what you want to measure.

In this case you might want to take a look at some of the lower-level primitives like `with-profiling` and `capture-time!`. Using these you can basically time whatever you want, using any concurrency mechanisms you like.

The downside is it'll need a little more work from you since you'll need to be quite explicit about what you want timed.

Hope that helps!

**Comment by vemv** [comment]
Hey there, thanks for the quick reply!

>  If you're using things like go blocks, then there's no way for Tufte to automatically know precisely what you want to measure.

Note that I'm not using them manually, it's simply that the web framework (3rd party) internally uses go blocks. So profiling `my/defn` should be straightforward: it will take the same amount of time whether it's hit from a go block, or directly.

> Using these you can basically time whatever you want, using any concurrency mechanisms you like.

Yes, I could hack something with approximately the following shape:

```clj
(tufte/with-profiling (tufte/new-pdata {:dynamic? true}) {:dynamic? true}
  (tufte/capture-time! pd ::foo 100)
  (println (tufte/format-pstats (deref pd))))
```

The printed results seem sound.

Should I worry about this warning?https://github.com/ptaoussanis/tufte/blob/a457b3f32cef7b7ddbc8ceeb37d907fb1b6df1c9/src/taoensso/tufte.cljc#L290

**Comment by ptaoussanis** [comment]
> Should I worry about this warning?

>>  Dynamic (thread-safe) by default.
  *WARNING*: don't change this default unless you're very sure the resulting
  pdata object will not be concurrently modified across threads. Concurrent
  modification will lead to bad data and/or exceptions!

You should be fine so long as you don't change the default `:dynamic?` argument when calling `new-pdata`.

**Comment by vemv** [comment]
Thanks!

I think we're all set.

Perhaps, consider making a more prominent warning in the README - currently this is one of the latest items in the FAQ.

By reading https://github.com/ptaoussanis/tufte/tree/a457b3f32cef7b7ddbc8ceeb37d907fb1b6df1c9#whats-the-difference-between-thread-local-and-dynamic-multi-threaded-profiling + https://github.com/ptaoussanis/tufte/tree/a457b3f32cef7b7ddbc8ceeb37d907fb1b6df1c9#how-do-i-get-dynamic-multi-threaded-profiling , one can get the mistaken idea that `dynamic?` is the only available alternative for multithreaded scenarios.

**Comment by ptaoussanis** [comment]
> one can get the mistaken idea that dynamic? is the only available alternative for multithreaded scenarios.

Did you see the following?:

> #### What if I want to time something across a promise / async handler / etc.?
> A low-level util (capture-time!) is provided for this and similar use cases. See its docstring for more info.

**Comment by vemv** [comment]
I did, but as the last step

e.g. 

1.- read https://github.com/ptaoussanis/tufte/tree/a457b3f32cef7b7ddbc8ceeb37d907fb1b6df1c9#whats-the-difference-between-thread-local-and-dynamic-multi-threaded-profiling + https://github.com/ptaoussanis/tufte/tree/a457b3f32cef7b7ddbc8ceeb37d907fb1b6df1c9#how-do-i-get-dynamic-multi-threaded-profiling 
2.- play with those and see that they don't work
3.- forget that there was more README to read, since I spent 30m in `2.-`

Also, `What if I want to time something across a promise / async handler / etc.?` doesn't really read like warning. Note that originally I perceived bug-like, and nothing in the code I had written explicitly had promises or async code.

A beginner may not even realise that his framework is running core.async at all, so he'd be extra confused.

Hope it helps!

**Comment by ptaoussanis** [comment]
> Also, What if I want to time something across a promise / async handler / etc.? doesn't really read like warning.

Sure, it's definitely not a warning. To clarify: what warning do you believe would be helpful? Maybe you could suggest a change for the README?
