### ISSUE TITLE
Formatting as documented in the README seems to have no effect

### ISSUE THREAD

**Issue by Reefersleep** [ptaoussanis/tufte#62]
Hey, thanks for a great lib! I Thoroughly enjoy using it.

I tried getting a bit better at using it, and it seems that 
```
(tufte/add-basic-println-handler!
  {:format-pstats-opts {:columns [:n-calls :p50 :mean :clock :total]
                        :format-id-fn name}})
```
, which is documented in the README as a way to format output, has absolutely no effect on the printed output.

EDIT: My theory didn't make sense.
I don't know why it doesn't work.

**Comment by ptaoussanis** [comment]
@Reefersleep Hi Søren. Are you sure there's no typos in your call? And that you're using the latest version of Tufte (2.2.0)?

Seems to work as expected on my end:

```clojure
(add-basic-println-handler! {:format-pstats-opts {:columns [:n-calls]}})
(profile {} (p :foo (Thread/sleep 1000)))
;; => prints with just nCalls

(add-basic-println-handler! {:format-pstats-opts {:columns [:n-calls :mean]}})
(profile {} (p :foo (Thread/sleep 1000)))
;; => prints with nCalls and Mean
```

**Comment by Reefersleep** [comment]
My bad; we weren't on the latest version of Tufte, like you said :) Thanks again, and sorry for wasting your time :/

**Comment by ptaoussanis** [comment]
No worries, thanks for updating 👍
