### ISSUE TITLE
Support defmethodp same as fnp and defnp

### ISSUE THREAD

**Issue by robert-stuttaford** [ptaoussanis/tufte#65]
So that we don't have `(p :some-keyword ...)` boilerplate inside each `defmethod`

**Comment by ptaoussanis** [comment]
@robert-stuttaford Hi Robert,

I haven't given this much thought - but my first inclination would be to say that there's too much variation in how multimethods may be implemented to include something out-the-box.

You can certainly avoid the `defmethod` boilerplate though, e.g.:

```clojure
(defn my-dispatch-fn [map-arg] (:dispatch-on map-arg))
(defmulti my-method my-dispatch-fn)

(defn my-method-profiled [map-arg]
  (let [dispatch-val (my-dispatch-fn map-arg)
        pid (keyword "my-method" (name (enc/have keyword? dispatch-val)))]

    (tufte/p pid
      (my-method map-arg))))

(defmethod my-method :kind1 [x] "kind1")

(let [[_ pstats]
      (tufte/profiled {}
        (my-method-profiled {:dispatch-on :kind1}))]
  @pstats))
```

I.e. by creating a small wrapper for the multifn that:
- Identifies the dispatch val
- Uses the  dispatch val to create an appropriate profiling form id (pid)

Creating a 1-size-fits-all wrapper like this could be limiting though. For example:
- What if calculating the dispatch value is expensive? Then you may want to avoid calling `my-dispatch-fn` twice, something a custom wrapper could easily do but that may be tricky at a library level without forcing constraints on the consumer.
- One may reasonably want to control how the pid is generated from the dispatch val.

Something could probably be made to work, but it's not immediately obvious to me that the particular combination would make sense for:
- How often a built-in util for this would be useful
- How much effort it'd save over something manual like the example above, esp. given the limitations a util might impose

Happy to hear your thoughts though, e.g.:
- Did you have some kind of specific API in mind?
- Is this an issue you run into regularly?
- Have you previously considered a wrapper like the above?

Cheers!

**Comment by robert-stuttaford** [comment]
Amazing, thank you Peter, I will work through your suggestions and see where I land. Thank you for such a quick and considered response!

**Comment by robert-stuttaford** [comment]
Closing; using the approach you suggest is completely sufficient for our needs.

To answer your question, in our case, the dispatch function is very lightweight, so it didn't even occur to me to think about profiling it, or the performance of that function!

```clojure
(defn perform-handler-dispatch [{:keys [action]}]
  action)
```

**Comment by ptaoussanis** [comment]
👍 Great, thanks for the confirmation Robert - cheers!
