### ISSUE TITLE
{:dynamic? true} does not report profilings inside callables in Executor pools

### ISSUE THREAD

**Issue by x** [ptaoussanis/tufte#9]
Using tufte 1.2 I can't profile statements wrapped in a `p` when they're clalled inside a callable executed in an `java.util.concurrent Executors` pool even when `dynamic?` is `true`.

The expected behavior here is that both `:foo` and `:bar` are reported. Instead, only `:foo` is (the `p` taking place in the main thread.
```clojure
user=> (import '[java.util.concurrent Executors])
nil
user=> (require '[taoensso.tufte :as tufte :refer [p profile]])
nil
user=> (profile {:dynamic? true} 
         (let [pool (Executors/newFixedThreadPool 5) 
               task (.submit pool (cast Callable (fn [] (p :foo (Thread/sleep 1000)))))] 
           (p :bar (.get task))))

           pId      nCalls       Min        Max       MAD      Mean   Time% Time
          :bar           1     1.01s      1.01s       0ns     1.01s     100 1.01s
    Clock Time                                                          100 1.01s
Accounted Time                                                          100 1.01s

nil
```

`^:dynamic` vars seems to work without an issue with executor pools so the expected behavior would be for this to work.
```clojure
user=> (def ^:dynamic *foo* "foo")
#'user/*foo*
user=> (let [pool (Executors/newFixedThreadPool 5) 
             task (.submit pool (cast Callable (fn [] (println *foo*))))] 
         (.get task))
foo
nil
```

**Comment by ptaoussanis** [comment]
Not at a computer atm, but have you tried blocking to allow the future time
to complete?

If the main thread terminates before the extra thread finishes, the main
thread won't be able to incorporate the incomplete stats.

**Comment by ptaoussanis** [comment]
Okay, had a chance to look at your issue more closely - the problem is here:

> ^:dynamic vars seems to work without an issue with executor pools so the expected behavior would be for this to work.

Clojure's automatic binding convenance does not work with executor pools.

```clojure
(do
  (def ^:dynamic *foo* nil)
  (binding [*foo* "foo"]
    (let [pool (Executors/newFixedThreadPool 5)
          task (.submit pool (cast Callable (fn [] (println *foo*))))] 
      (.get task))))
```

Your example provided a root binding at `(def ^:dynamic *foo* "foo")` so wasn't actually testing binding conveyance.

If you want automatic binding conveyance, you'll need to use a Clojure `future`- otherwise you can get manual binding conveyance with `bound-fn`, or something like `binding-conveyor-fn`, etc.

Hope that helps, cheers! :-)
